version: "3.8"
services:
  elk:
    image: sebp/elk:780
    restart: always
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d:ro
      - elk:/var/lib/elasticsearch
    networks: 
      shared-net:
        aliases: 
          - kibana
          - logstash
          - elasticsearch
  nginx-app-protect:
    image: nap:juice-shop
    restart: always
    networks: 
      shared-net:
        aliases: 
          - nginx
    ports:
      - "80:80" #app protect
      - "81:81" #kibana
      - "443:443"
      - "8080:8080" #status api
  juice-shop:
    image: bkimminich/juice-shop
    restart: always
    networks: 
      shared-net:
        aliases: 
          - juice-shop
    ports:
      - "3000:3000" 
networks: 
  shared-net:
    external: true
    name: shared-net
volumes:
  elk:
