version: "3.8"
services:
  elasticsearch:
    image: sebp/elk:780
    restart: always
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d:ro
      - elk:/var/lib/elasticsearch
    networks: 
      shared-net:
        aliases: 
          - syslog
          - kibana
          - logstash
networks: 
  shared-net:
    external: true
    name: shared-net
volumes:
  elk:
